### ISSUE TITLE
how to generate the nii.gz mask 

### ISSUE THREAD

**Issue by damao4123** [lihengbit/PROSTATEx#1]
hello liheng:
     i was looking for a regiongrow function in prostateX, and i found you.
     in your code i see lots of 'nii.gz' files,such as 'ProstateX-0000_BVAL_1.nii.gz', but i don't know how to generate these files, can you explain this to me, please

thank you

**Comment by liamheng** [comment]
Hi,
I used 3D Slicer to convert the data into Nifti format.
Hope it can help you.

Best

**Comment by damao4123** [comment]
尊敬的lihengbit：
       十分感谢您！
       解决了我困扰已久的问题。
       我看到在regiongrow.py里，还用到了"Tra_Mask.nii.gz"，我研究了您的工程，没有找到这个横断面的mask是如何生成的。
       此外，您研究的regiongrow算法在prostateX数据集上的效果怎样，渴望您能分享。
       以上两点疑惑，期望您回复

再次感谢

**Comment by liamheng** [comment]
原始数据中有ROI的中心点，我是使用这个中心点周围区域进行的regiongrow，但是数据中没有Mask的groundtruth，所以我只是肉眼看了一下结果，比直接用中心点好一些。我没有做更精细的分割。

**Comment by damao4123** [comment]
好的，懂了，再次感谢您的关注和回复！
